### ISSUE TITLE
Usage of the code

### ISSUE THREAD

**Issue by 000Justin000** [lettis/FastPCA#1]
Hello Lettis,

My name is Junteng Jia and I am a graduate student at Cornell University. Lately I am trying to calculate the principle components of a set of data. I successfully compiled your code (latest version), and I ran with the command:

$./fastpca --file test.txt --nthreads 8 --val eigenval.out --vec eigenvec.out

The test.txt file is very simple:
[test.txt](https://github.com/lettis/FastPCA/files/117874/test.txt)

However, I ran into the problem "Segmentation fault". Do you know what is going on here ?

Thanks a million !

Best,
Junteng

**Comment by lettis** [comment]
Dear Junteng,
thank you for your feedback.
Some days ago I changed the menu structure of the code, which introduced the bug.
This reminds me that I should get some unit cases written...
I tested the updated code with your example, it now produces the expected results.

Cheers,
  Florian

**Comment by 000Justin000** [comment]
Dear Lettis,

Thanks for your feedback ! Now the code gives correct result for the test case I used before.
However, when I am trying to use this program to analysis our data, I ran into "std::bad_alloc" error.
My data set is a vector of size 100000, I guess that might be a problem. Is there a way I can use to make it work ? 

Thank you again !
Best Regards,
Junteng
