### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by simonbray** [lettis/FastPCA#3]
Hi Daniel @moldyn-nagel,

I don't know if Steffen already discussed this with you, but I'm currently working on a fastpca conda package. The package should ideally be built from an official version of the software, so I tried from the 0.9 release (commit https://github.com/lettis/FastPCA/commit/d8df689faed85dde5f982f5164235e9ac6f64931). However, compilation fails, whereas it succeeds for the latest commit on the master branch.

Could you therefore create a new version on GitHub under https://github.com/moldyn/FastPCA/releases (0.10, 0.9.1 or similar) corresponding to the latest commit?

Thanks, Simon

**Comment by moldyn-nagel** [comment]
Hi Simon,
yes for sure. But only in the fork were I have access to [moldyn fastPCA](https://github.com/moldyn/FastPCA). I'll push it later this afternoon.

Best, Daniel
PS: The master does not compile for new versions of openMP. I fixed it locally, but I should test it before pushing it.

**Comment by simonbray** [comment]
Sounds good, I can also test after you push.
